# These will be sorted first in that order.
# All packages that are depended upon by others should be listed here.
[DEFAULT]

sortfirst=
    util/opentelemetry-util-genai
    instrumentation/*

[prerelease]
version=1.0b0.dev

packages=
    all
    opentelemetry-util-genai

[exclude_release]
packages=
    opentelemetry-instrumentation-genai-anthropic
    opentelemetry-instrumentation-genai-claude-agent-sdk
    opentelemetry-instrumentation-google-genai
    opentelemetry-instrumentation-genai-langchain
    opentelemetry-instrumentation-genai-openai
    opentelemetry-instrumentation-genai-openai-agents
    opentelemetry-instrumentation-genai-weaviate-client
    opentelemetry-util-genai

[lintroots]
extraroots=examples/*,scripts/
subglob=*.py,tests/,test/,src/*,examples/*

[testroots]
extraroots=examples/*,tests/
subglob=tests/,test/
