name: _Prepare release package
on:
  workflow_call:
    inputs:
      package:
        required: true
        type: string
      pr_title_prefix:
        required: false
        type: string
        default: ""
      add_release_label:
        required: false
        type: boolean
        default: false

permissions:
  contents: read

jobs:
  prepare:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Verify prerequisites
        run: |
          if [[ "$GITHUB_REF_NAME" != "main" ]]; then
            echo "This workflow should only be run against main"
            exit 1
          fi

          version_dev=$(./scripts/eachdist.py version --package ${{ inputs.package }})
          if [[ ! "$version_dev" =~ \.dev$ ]]; then
            echo "Expected a .dev version on main, got ${version_dev}"
            exit 1
          fi

          echo "VERSION=${version_dev%.dev}" >> $GITHUB_ENV
          echo "PACKAGE_NAME=${{ inputs.package }}" >> $GITHUB_ENV

      - name: Set up Python 3.10
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: '3.14'

      - name: Install tox and towncrier
        run: |
          pip install tox towncrier==25.8.0

      - name: Prepare package for release
        run: ./scripts/prepare_package_for_release.sh "${{ inputs.package }}"

      - name: Use CLA approved github bot
        run: .github/scripts/use-cla-approved-github-bot.sh

      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: otelbot-token
        with:
          app-id: ${{ vars.OTELBOT_APP_ID }}
          private-key: ${{ secrets.OTELBOT_PRIVATE_KEY }}

      - name: Create pull request against main
        env:
          GITHUB_TOKEN: ${{ steps.otelbot-token.outputs.token }}
        run: |
          prefix="${{ inputs.pr_title_prefix }}"
          message="${prefix}Prepare release for ${PACKAGE_NAME} v${VERSION}"
          body="Prepare \`${PACKAGE_NAME}\` v\`${VERSION}\` for release."
          branch="otelbot/prepare-${PACKAGE_NAME}-v${VERSION}"

          git commit -a -m "$message"
          git push origin HEAD:"$branch"
          pr_url=$(gh pr create --title "$message" \
                                --body "$body" \
                                --head "$branch" \
                                --base main \
                                --json url --jq .url)

          if [[ "${{ inputs.add_release_label }}" == "true" ]]; then
            gh pr edit "$pr_url" --add-label release
          fi
