name: "[Package] Prepare release"
on:
  workflow_dispatch:
    inputs:
      package:
        type: choice
        options:
        - opentelemetry-instrumentation-genai-anthropic
        - opentelemetry-instrumentation-google-genai
        - opentelemetry-instrumentation-genai-langchain
        - opentelemetry-instrumentation-genai-openai-agents
        - opentelemetry-instrumentation-genai-openai
        - opentelemetry-util-genai
        description: 'Package to be released'
        required: true

permissions:
  contents: read

run-name: "[Package][${{ inputs.package }}] Prepare release"

jobs:
  prepare:
    uses: ./.github/workflows/_prepare-release-package.yml
    with:
      package: ${{ inputs.package }}
    secrets: inherit
